### ISSUE TITLE
Keycaps

### ISSUE THREAD

**Issue by donkeybanana** [ozkan/Yakamoz#1]
Hi, nice work on the board.

If you don't mind me asking, what's the name of the keycaps set in the readme image?

Thanks

**Comment by Ardakilic** [comment]
Hey there, it's my very board and are my very keycaps. Glad you like them 😊 

Nothing fancy though. They are generic cheap XDA PBT keycaps from Aliexpress.

I got them from this store: https://www.aliexpress.com/item/1005005732048287.html . It's $13 (+tax), shipped, from China to my Country.
